name: Scrape ERTFlix Movies

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # --- Η ΣΩΣΤΗ, ΑΞΙΟΠΙΣΤΗ ΜΕΘΟΔΟΣ ΓΙΑ CHROME ---
      - name: Set up Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@latest

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push if there are changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ertflix_playlist.m3u8
          git diff --staged --quiet || (git commit -m "Update ERTFlix movie playlist" && git push)

      # --- ΠΡΟΣΘΕΣΕ ΑΥΤΟ ΤΟ ΚΟΜΜΑΤΙ ΣΤΟ ΤΕΛΟΣ ---
      - name: Upload debug artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: debug-artifacts
          path: |
            debug_screenshot.png
            debug_page_source.html
