name: Scrape ERTFlix Movies

on:
  # Εκτελείται αυτόματα μία φορά την ημέρα
  schedule:
    - cron: '0 3 * * *'
  # Επιτρέπει τη χειροκίνητη εκτέλεση από το tab "Actions" του GitHub
  workflow_dispatch:

# Δίνει στο action την άδεια να κάνει 'commit' και 'push' στο αποθετήριο
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push if there are changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          # Βεβαιωθείτε ότι αυτό το όνομα ταιριάζει με το OUTPUT_FILE στο scraper.py
          git add ertflix_playlist.m3u8
          git diff --staged --quiet || git commit -m "Update ERTFlix movie playlist"
          git push
