name: Scrape Skai TV Movies

on:
  # Εκτελείται αυτόματα κάθε μέρα στις 03:00 UTC (06:00 ώρα Ελλάδας το καλοκαίρι)
  schedule:
    - cron: '0 3 * * *'
  # Επιτρέπει τη χειροκίνητη εκτέλεση από το tab "Actions" του GitHub
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push if there are changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add skai_playlist.m3u8
          # Κάνε commit μόνο αν υπάρχουν αλλαγές στο αρχείο
          git diff --staged --quiet || git commit -m "Update movie playlist"
          git push
